spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.46:3306/cloud2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
server:
  port: 8003
  servlet:
    context-path: /payment
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:/META-INF/mybatis/mybatis-config.xml
