server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 192.168.10.46
      port: 8500
      discovery:
        heartbeat:
          enabled: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_route1
          uri: lb://cloud-provider-payment #负载均衡
          predicates:
            - Path=/payment/gateway/get/**
        - id: pay_route2
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/gateway/info
            #- After=2024-04-08T22:40:30.586918800+08:00[Asia/Shanghai] #在某个时间之后可以访问
            #- Before=2024-04-08T22:42:30.586918800+08:00[Asia/Shanghai] #在某个时间之前可以访问
            #- Between=2024-04-08T22:44:00.586918800+08:00[Asia/Shanghai],2024-04-08T22:44:20.586918800+08:00[Asia/Shanghai] #在某个时间段之内可以访问
            #- Cookie=username,chenzzZ #访问时要带有cookie,且cookie的值是 username:chenzzZ
            #- Header=X-Request-Id,\d+ #访问时要带有请求头X-Request-Id,并且要为整数
            #- Host=**.chen.xiansen.com #访问时的Host以chen.xiansen.com结尾
            #- Query=username, \d+ #访问时带有username参数,并且为整数
            #- RemoteAddr=192.168.10.1/24 #限制外部访问时的ip
            #- Method=GET,POST #限制访问方式
