server:
  port: 8090
  servlet:
    context-path: /order
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.1.12
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true