server:
  port: 8002
  servlet:
    context-path: /payment
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.46:3306/cloud2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  profiles:
    active: dev
mybatis:
  config-location: classpath:META-INF/mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

