spring:
  r2dbc:
    username: root
    password: 123456
    url: r2dbc:mysql://192.168.10.46:3306/test
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
server:
  port: 8090

